EDU.Web/ViewModels/Master/CourseSalesMasterVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using EZY.EDU.Contract;
using EDU.Web.ViewModels.CourseDetail;

namespace EDU.Web.ViewModels.Master
{
    public class CourseSalesMasterVm
    {
        public CourseSalesMaster courseSalesMaster { get; set; }

        public IEnumerable<Branch> branchList { get; set; }

        public IEnumerable<Course> courseList { get; set; }

        public IEnumerable<EduProduct> eduProductList { get; set; }

        public IEnumerable<MonthVm> monthList { get; set; }
    }
}

EDU.Web/Controllers/MasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using EZY.EDU.Contract;
using EZY.EDU.BusinessFactory;

using EDU.Web.ViewModels.Master;

namespace EDU.Web.Controllers
{
    [SessionFilter]
    public class MasterController : BaseController
    {

        [HttpGet]
        public JsonResult GetCoursesByProductCoutry(int Id, short country)
        {
            var courseList = new CourseBO().GetCoursesByProductCoutry(Id, country);
            return Json(courseList, JsonRequestBehavior.AllowGet);
        }



        #region EduProduct
        [HttpGet]
        public ViewResult EduProductList()
        {
            var list = new EduProductBO().GetList();
            return View("EduProductList", list.AsEnumerable());
        }

        [HttpGet]
        public PartialViewResult EduProduct(int? Id)
        {
            if (!Id.HasValue)
            {
                ViewBag.Title = "New Product";
                return PartialView(new EduProduct { Id = -1, IsActive = true });
            }
            else
            {
                ViewBag.Title = "Update Product";
                return PartialView(new EduProductBO().GetEduProduct(new EduProduct { Id = Id.Value }));

            }
        }

        [HttpPost]
        public RedirectToRouteResult SaveEduProduct(EduProduct eduProduct)
        {
            eduProduct.ProductDescription = eduProduct.ProductName;

            eduProduct.CreatedBy = USER_ID;
            eduProduct.CreatedOn = UTILITY.SINGAPORETIME;
            eduProduct.ModifiedBy = USER_ID;
            eduProduct.ModifiedOn = UTILITY.SINGAPORETIME;
            if (!IsEduProductExists(eduProduct.ProductName))
            {
                var result = new EduProductBO().SaveEduProduct(eduProduct);
            }

            return RedirectToAction("EduProductList");
        }

        [HttpPost]
        public ActionResult DeleteEduProduct(int? Id)
        {
            var result = new EduProductBO().DeleteEduProduct(new EduProduct { Id = Id.Value });

            var list = new EduProductBO().GetList();
            return View("EduProductList", list.AsEnumerable());
        }


        [HttpGet]
        public bool IsEduProductExists(string productName)
        {
            return new EduProductBO().IsEduProductExists(new EduProduct { ProductName = productName });
        }

        #endregion

        #region Course
        [HttpGet]
        public ViewResult CourseList()
        {
            var list = new CourseBO().GetList().ToList();

            if (Session["AccessRights"].ToString() == "false")
            {
                list = list.Where(x => x.Country == Convert.ToUInt16(Session["BranchId"])).ToList();
            }

            return View("CourseList", list);
        }

        [HttpGet]
        public ViewResult CourseListSearch(string search)
        {
            var list = new CourseBO().GetList();
            ViewData["SearchText"] = search;
             list = list.Where(x=>x.CountryName.ToLower().Contains(search) ||
                x.ProductName.ToLower().Contains(search) || 
                x.CourseName.ToLower().Contains(search) || 
                x.NoOfDays.ToString().ToLower().Contains(search) || 
                x.PublicPrice.ToString().ToLower().Contains(search) || 
                x.PrivatePrice.ToString().ToLower().Contains(search))
                .ToList();
            return View("CourseList", list);
        }

        [HttpGet]
        public PartialViewResult Course(int? Id)
        {
            ViewData["ProductData"] = new EduProductBO().GetList();
            ViewData["CountryData"] = new BranchBO().GetList();

            Course course = new Course();
            if (!Id.HasValue)
            {
                ViewBag.Title = "New Regional Costing";
                course = new Course { Id = -1, IsActive = true };
            }
            else
            {
                ViewBag.Title = "Update Regional Costing";
                course = new CourseBO().GetCourse(new Course { Id = Id.Value });
                ViewData["CourseData"] = new CourseBO().GetCoursesByProduct(course.Product).AsEnumerable();
            }
            return PartialView(course);
        }

        [HttpGet]
        public JsonResult GetCourse(int Id)
        {
            return Json(new CourseBO().GetCourse(new Course { Id = Id }), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public RedirectToRouteResult SaveCourse(Course course)
        {
            if (course.CourseDescription != null && course.CourseDescription != "")
            {
                course.CourseName = course.CourseDescription;
            }
            else
            {
                Course courseDtl = new CourseBO().GetCourse(new Course { Id = Convert.ToInt32(course.CourseName) });
                course.CourseName = courseDtl.CourseName;
                course.CourseDescription = course.CourseName;
            }


            course.CreatedBy = USER_ID;
            course.CreatedOn = UTILITY.SINGAPORETIME;
            course.ModifiedBy = USER_ID;
            course.ModifiedOn = UTILITY.SINGAPORETIME;
            course.AvailableSeats = 0;
            var result = new CourseBO().SaveCouse(course);

            return RedirectToAction("CourseList");
        }


        [HttpPost]
        public ActionResult DeleteEduCourse(int? Id)
        {
            var result = new CourseBO().DeleteEduCourse(new Course { Id = Id.Value });

            var list = new CourseBO().GetList();
            if (Session["AccessRights"].ToString() == "false")
            {
                list = list.Where(x => x.Country == Convert.ToUInt16(Session["BranchId"])).ToList();
            }
            return View("CourseList", list);
        }

        [HttpGet]
        public bool IsEduCourseExists(string courseName, short country, int product)
        {
            return new CourseBO().IsEduCourseExists(new Course { CourseName = courseName, Country = country, Product = product, });
        }
        #endregion

        #region Course Sales Master
        [HttpGet]
        public ViewResult CourseSalesMasterList(short month, int year)
        {
            var list = new CourseSalesMasterBO().GetList();
            if (month == 0)
                list = list.Where(x => x.Year == year).ToList();
            else
                list = list.Where(x => x.Year == year && x.Month == month).ToList();

            if (Session["AccessRights"].ToString() == "false")
            {
                list = list.Where(x => x.Country ==Convert.ToUInt16(Session["BranchId"])).ToList();
            }

            //var totalleadsonhand = 0;
            //long totalrevenue = 0;

            //foreach (var item in list)
            //{
            //    totalleadsonhand += item.LeadsOnHead;
            //    totalrevenue += Convert.ToInt64(item.Revenue == null ? 0 : item.Revenue.Value);
            //}

            //ViewData["totalleadsonhand"] = totalleadsonhand;
            //ViewData["totalrevenue"] = totalrevenue;

            ViewData["ProductList"] = new EduProductBO().GetList().OrderBy(x => x.Id).ToList();
            return View("CourseSalesMasterList", list.AsEnumerable());
        }

        [HttpGet]
        public ViewResult CourseSalesMaster(int Id, short month, int year)
        {
            CourseSalesMaster courseSalesMaster = null;
            var courseSalesMasterVm = new CourseSalesMasterVm
            {
                eduProductList = new EduProductBO().GetList().AsEnumerable(),
                branchList = new BranchBO().GetList().AsEnumerable(),
                monthList = GetMonthData(),
                courseSalesMaster = courseSalesMaster
            };

            if (Id == -1)
            {
                courseSalesMaster = new CourseSalesMaster
                {
                    Id = Id,
                    Year = year
                    //StartDate = UTILITY.SINGAPORETIME,
                    //EndDate = UTILITY.SINGAPORETIME,
                    //RegClosingDate = UTILITY.SINGAPORETIME.AddDays(-14)
                };
            }
            else
            {
                courseSalesMaster = new CourseSalesMasterBO()
                                            .GetCourseSalesMaster(new CourseSalesMaster { Id = Id });
                courseSalesMaster.Year = year;

                courseSalesMasterVm.courseList = new CourseBO()
                                                    .GetCoursesByProductCoutry(courseSalesMaster.Product, courseSalesMaster.Country)
                                                    .AsEnumerable();
            }

            courseSalesMasterVm.courseSalesMaster = courseSalesMaster;
            ViewData["month"] = month;
            return View("CourseSalesMaster", courseSalesMasterVm);
        }

        [HttpPost]
        public RedirectToRouteResult CoureSalesMaster(CourseSalesMaster courseSalesMaster, int mnth)
        {
            courseSalesMaster.IsActive = true;
            courseSalesMaster.CreatedBy = USER_ID;
            courseSalesMaster.CreatedOn = UTILITY.SINGAPORETIME;
            courseSalesMaster.ModifiedBy = USER_ID;
            courseSalesMaster.ModifiedOn = UTILITY.SINGAPORETIME;
            courseSalesMaster.ConfirmOrDropDate = UTILITY.SINGAPORETIME;

            courseSalesMaster.Id = new CourseSalesMasterBO().SaveCourseSalesMaster(courseSalesMaster);
            return RedirectToAction("CourseSalesMasterList", new { month = mnth, year = courseSalesMaster.Year });
        }


        [HttpPost]
        public ActionResult DeleteCourseSalesMaster(int? Id, short month, int year)
        {
            var result = new CourseSalesMasterBO().DeleteCourseSalesMaster(new CourseSalesMaster { Id = Id.Value });

            var list = new CourseSalesMasterBO().GetList().Where(x => x.Year == year && x.Month == month);
            var totalleadsonhand = 0;

EDU.Web/Views/Master/Course.cshtml
@model EZY.EDU.Contract.Course
<div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">@ViewBag.Title</h4>
        </div>
        <div class="modal-body" id="ProductCategoryModalBody">
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.IsActive)
            <input type="hidden" id="cname" name="cname" />
            <div class="row">
                <div class="form-group">
                    <label class="col-md-3 control-label col-md-offset-1">
                        <span>Country</span>
                    </label>
                    <div class="col-md-4">
                        @Html.DropDownListFor(x => x.Country,
                    new SelectList((List<EZY.EDU.Contract.Branch>)ViewData["CountryData"], "BranchID", "BranchName"),
                    "Select Country", new { @class = "form-control input-sm", onchange = "CountryChange(this);" })
                    </div>
                </div>
            </div>
            <div class="row css10">
                <div class="form-group">
                    <label class="col-md-3 control-label col-md-offset-1">
                        <span>Product</span>
                    </label>
                    <div class="col-md-4">
                        @Html.DropDownListFor(x => x.Product,
                    new SelectList((List<EZY.EDU.Contract.EduProduct>)ViewData["ProductData"], "Id", "ProductName"),
                    "Select Product", new { @class = "form-control input-sm", onchange = "ProductChange(this);" })
                    </div>
                </div>
            </div>
            <div class="row css10" id="existCourse">
                <div class="form-group">
                    <label class="col-md-3 control-label col-md-offset-1">
                        <span>Course Name</span>
                    </label>
                    <div class="col-md-4">
                        @if (Model.Id == -1)
                        {
                            @Html.DropDownListFor(x => x.CourseName,
                                Enumerable.Empty<SelectListItem>(),
                                "Select Course",
                                new { @class = "form-control input-sm", disabled = "disabled", onchange = "CourseChange(this)" })
                        }
                        else
                        {
                            @Html.DropDownListFor(x => x.CourseName,
                                                 new SelectList((List<EZY.EDU.Contract.Course>)ViewData["CourseData"], "Id", "CourseName"),
                                             "Select Course",
                                        new { @class = "form-control input-sm", onchange = "CourseChange(this)" })
                        }
                    </div>
                    <div class="col-md-1">
                        <button type="button" class="btn btn-info btn-xs waves-effect" onclick="enableCourseText()"><i class="fa fa-plus" style="padding-left: 5px;"></i>Add New Course</button>

                    </div>
                </div>
            </div>
            <div class="row css10" id="newCourse">
                <div class="form-group">
                    <label class="col-md-3 control-label col-md-offset-1">
                        <span>New Course Name</span>
                    </label>
                    <div class="col-md-7">
                        @Html.TextAreaFor(x => x.CourseDescription,
                    new { @class = "form-control input-sm", placeholder = "Course Name" })@*, onblur = "ValidateCourseName(true)"*@
                </div>
                <div class="col-md-1">
                    <button type="button" class="btn btn-danger btn-xs waves-effect" onclick="disableCourseText()"><i class="fa fa-times" style="padding-left: 5px;"></i></button>
                </div>
            </div>
        </div>
        <div class="row css10">
            <div class="form-group">
                <label class="col-md-3 control-label col-md-offset-1">
                    <span>No. Of Days</span>
                </label>
                <div class="col-md-4">
                    @Html.DropDownListFor(x => x.NoOfDays, Enumerable.Range(0, 11).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }), "Select", new { @class = "form-control input-sm" })
                </div>
            </div>
        </div>
        <div class="row css10">
            <div class="form-group">
                <label class="col-md-3 control-label col-md-offset-1">
                    <span>Public Price</span>
                </label>
                <div class="col-md-4">
                    @Html.TextBoxFor(x => x.PublicPrice,
                    new { @class = "form-control numCss input-sm", placeholder = "Public Price", @Value = Convert.ToInt64(Model.PublicPrice) })
                </div>
            </div>
        </div>
        <div class="row css10">
            <div class="form-group">
                <label class="col-md-3 control-label col-md-offset-1">
                    <span>Private Price</span>
                </label>
                <div class="col-md-4">
                    @Html.TextBoxFor(x => x.PrivatePrice,
                    new { @class = "form-control numCss input-sm", placeholder = "Private Price", @Value = Convert.ToInt64(Model.PrivatePrice) })
                </div>
            </div>
        </div>

        <div class="modal-footer css10">
            <button type="button" id="btnSave" onclick="SaveCourse()" class="btn btn-success btn-frmt btn-sm"> <i class="fa fa-floppy-o"></i>&nbsp;Save</button>
            <button type="button" class="btn btn-default btn-frmt btn-sm" data-dismiss="modal"><i class="fa fa-times"></i>Close</button>
        </div>
    </div>
</div>

</div>
<style type="text/css">
    .select2 {
        width: 172px !important;
    }
</style>
<script type="text/javascript">
    $(function () {
        $('#newCourse').hide();
        $("select").select2();
    @if (Model.Id == -1)
    {
        if (Session["AccessRights"].ToString() == "false")
        {
            <text>
                $("#Country").select2().select2("val", @Session["BranchId"].ToString());
                $('#Country').attr('disabled', 'disabled');
            </text>
        }
    }
    });

    $('select').select2({}).on("change", function (e) {
        $(this).valid()
    });
    function disableCourseText() {
        $('#CourseDescription').val('');
        $('#newCourse').hide();
        $('#existCourse').show();
    }
    function enableCourseText() {
        $('#CourseName').val('');
        $('#CourseDescription').val('');
        $('#newCourse').show();
        $('#existCourse').hide();
    }
      @*  @if(Model.Id != -1)
        {
            <text>
        $(function () {
            $('#CourseName, #Country, #Product').attr('disabled', 'disabled');
        });
            </text>
        }*@
</script>

EDU.Web/Views/Master/EduProduct.cshtml
@model EZY.EDU.Contract.EduProduct
<div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">@ViewBag.Title</h4>
        </div>
        <div class="modal-body">
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.IsActive)

            <div class="row">
                <div class="form-group">
                    <label class="col-md-4 control-label">
                        <span class="pull-right">Product Name</span>
                    </label>
                    <div class="col-md-8">
                        @Html.TextBoxFor(x => x.ProductName,
                    new
                    {
                        @class = "form-control input-sm",
                        placeholder = "Product Name",
                        onblur = "ValidateProductName(true)"
                    })
                        <label id="error" style="color:red">Product already exists. Please re-enter new product.</label>
                    </div>
                </div>
            </div>            
        </div>
        <div class="modal-footer">
            <button type="button" onclick="SaveEduProduct()" class="btn btn-success btn-frmt green btn-sm">
                <i class="fa fa-floppy-o"></i>&nbsp;Save
            </button>
            <button type="button" class="btn btn-default btn-frmt btn-sm" data-dismiss="modal"><i class="fa fa-times"></i>Close</button>
        </div>
    </div>

</div>

EDU.Web/Views/Master/EduProductList.cshtml
@model IEnumerable<EZY.EDU.Contract.EduProduct>
<div class="page">
    <div class="page-wrap">
        <div class="panel panel-default">

            <div class="row" style="margin-top:20px;">
            </div>
            <div class="box center" id="grid">
                <div class="box-header">
                    <h4>Product List</h4>
                    <div class="box-tools">
                        <button type="button" class="btn btn-primary btn-sm waves-effect" data-toggle="modal" onclick="PrintProductList()"><i class="fa fa-print"></i>Print</button>

                        @if (Session["RoleCode"].ToString() == "ADMIN" || Session["RoleCode"].ToString() == "REGIONAL")
                        {
                            <button class="btn btn-info btn-sm waves-effect" type="button" onclick="AddEduProduct();"><i class="fa fa-plus"></i> Add New Product</button>
                        }
                    </div>
                </div>

                <div class="box-body">
                    <div class="table-responsive">
                        <table class="table-bordered tblSearch" id="tblProduct" style="white-space:nowrap;width:100%">
                            <thead style="cursor:pointer">
                                <tr>
                                    <td style='width:60px;'>#Action</td>
                                    <td style='width:150px;'>Product</td>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @if (Session["RoleCode"].ToString() == "ADMIN" || Session["RoleCode"].ToString() == "REGIONAL")
                                            {
                                                <button class="btn btn-xs btn-success waves-effect" onclick="EditEduProduct(@item.Id)"><i class="fa fa-pencil-square-o" style="padding-left: 5px;"></i></button>
                                                <button class="btn btn-xs btn-danger waves-effect" onclick="DeleteProductCategory(@item.Id)"><i class="fa fa-trash-o" style="padding-left: 5px;"></i></button>
                                            }
                                        </td>
                                        <td>
                                            @item.ProductName
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


@using (Html.BeginForm("DeleteEduProduct", "Master", FormMethod.Post, new { id = "frmDelete", name = "frmDelete" }))
{
    <input type="hidden" id="id" name="id" />
}
@using (Html.BeginForm("SaveEduProduct", "Master", FormMethod.Post, new { id = "frmEduProduct", name = "frmEduProduct", autocomplete = "off" }))
{
    <div id="myModal" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">

    </div>
}
@section SectionScripts{
    <script type="text/javascript">
        $(function () {
            debugger;
            $('#liEduProductList').addClass('active');
        });
        function PrintProductList() {
            $.ajax({
                url: '@Url.Content("~/Report/ProductsReport")',
                method: 'get',
                contentType: 'text/html',
                success: function (html) {
                    $('#myModal').html(html);
                    $('#myModal').modal('show');
                },
                error: function (err) {
                }
            });
        }
        function AddEduProduct() {
            $.ajax({
                url: '@Url.Content("~/Master/EduProduct")',
                method: 'get',
                contentType: 'text/html',
                success: function (html) {
                    debugger;
                    $('#myModal').html(html);
                    $('#myModal').modal('show');
                    $('#error').hide();
                },
                error: function (err) {

                }
            });
        }
        function DeleteProductCategory(Id) {
            //if (confirm("Are you sure, do you want delete?")) {
            //    $('#id').val(Id);
            //    $('#frmDelete').submit();
            //}
            swal({
                title: "Are you sure?",
                text: "Do you want delete?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-danger",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: false
            },
            function () {
                $('#id').val(Id);
                $('#frmDelete').submit();
                swal("Deleted!", "Your product has been deleted.", "success");

            });
        }
        function EditEduProduct(Id) {
            $.ajax({
                url: '@Url.Content("~/Master/EduProduct?Id=")' + Id,
                method: 'get',
                contentType: 'text/html',
                success: function (html) {
                    $('#myModal').html(html);
                    $('#myModal').modal('show');
                    $('#error').hide();
                },
                error: function (err) {

                }
            });
        }

        debugger;
        $('#frmEduProduct').validate({
            rules: {
                ProductName:
                    {
                        required: true
                    }
            }
        })
        function SaveEduProduct() {
            debugger;
            if ($('#frmEduProduct').valid()) {
                $('#frmEduProduct').submit();
            }
        };
        function ValidateByProductName() {
            var def = $.Deferred();
            $.ajax({
                url: '@Url.Content("~/Master/IsEduProductExists?productName=")' + $('#ProductName').val(),
                method: 'get',
                contentType: 'text/html',
                success: function (result) {
                    def.resolve(result);
                }
            });
            return def.promise();
        };


        function ValidateProductName(isBlur) {
            var promise = ValidateByProductName();
            $.when(promise).done(function (result) {
                if (isBlur) {
                    if (result == "True") {
                        debugger;
                        $('#error').show();
                        //alert("Product already exists. Please re-enter new product.");
                        $('#ProductName').val('');
                    }
                    else {
                        $('#error').hide();
                    }
                }
                else {
                    return result
                }
            });
        };

    </script>
}

<style>
    .center {
        margin: auto;
        width: 45%;
        border: 3px solid gray;
        padding: 10px;
        border-radius: 20px;
    }

    .Grid-Footer > td {
        padding-top: 10px;
        text-align: right;
        margin-bottom: 10px;
    }

        .Grid-Footer > td > a {
            background: #fff;
            display: inline-block;
            border-radius: 1px;
            padding: 6px 12px;
            font-size: 16px;
            cursor: pointer;
            border: 2px solid #eeeeee;
        }

            .Grid-Footer > td > a:hover {
                color: #3f51b5;
                text-decoration: none;
            }
</style>