EDU.Web/Models/OperationalTransaction.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationalTransaction
    {
        public int OperationalTransactionId { get; set; }
        public int CategoryId { get; set; }
        public int ParticularsId { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<short> Month { get; set; }
        public decimal Amount { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public short Country { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> OperationId { get; set; }
    }
}

EDU.Web/Controllers/DashboardController.cs
using EDU.Web;
using EDU.Web.Models;
using EDU.Web.ViewModels.FinancialTransactionModel;
using EDU.Web.ViewModels.OperationalTransaction;
using EDU.Web.ViewModels.DashboardModel;
using EZY.EDU.BusinessFactory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;


namespace EDU.Web.Dashboard.Controllers
{
    [SessionFilter]
    public class DashboardController : BaseController
    {
        EducationEntities dbContext = new EducationEntities();

        public ActionResult Operationaltransaction(Int16 country, int month, int year)
        {
            try
            {
                var list = dbContext.usp_OperationalTransactionReport(year).ToList();

                OperationalTransactionReportVM reportList = new OperationalTransactionReportVM();
                if (list != null)
                {
                    reportList.otReportByMonth = list.Where(m => m.Month == month && m.Country == country)
                        .Select(x => new OperationalTransactionReportByMonth
                        {
                            ParticularName = x.ParticularName,
                            Amount = x.Amount,
                            Month = x.Month,
                            Country = x.Country,
                            Year = year,
                            CountryName = x.CountryName
                        }).ToList();

                    reportList.otReportByYear = list.Select(x => new OperationalTransactionReportByYear
                    {
                        Country = x.Country,
                        CountryName = x.CountryName,
                        JanAmount = list.Where(y => y.Month == 1 && y.Country == country).Count() > 0 ? list.Where(y => y.Month == 1 && y.Country == country).Sum(z => z.Amount) : 0,
                        FebAmount = list.Where(y => y.Month == 2 && y.Country == country).Count() > 0 ? list.Where(y => y.Month == 2 && y.Country == country).Sum(z => z.Amount) : 0,
                        MarAmount = list.Where(y => y.Month == 3 && y.Country == country).Count() > 0 ? list.Where(y => y.Month == 3 && y.Country == country).Sum(z => z.Amount) : 0,
                        AprAmount = list.Where(y => y.Month == 4 && y.Country == country).Count() > 0 ? list.Where(y => y.Month == 4 && y.Country == country).Sum(z => z.Amount) : 0,
                        MayAmount = list.Where(y => y.Month == 5 && y.Country == country).Count() > 0 ? list.Where(y => y.Month == 5 && y.Country == country).Sum(z => z.Amount) : 0,
                        JunAmount = list.Where(y => y.Month == 6 && y.Country == country).Count() > 0 ? list.Where(y => y.Month == 6 && y.Country == country).Sum(z => z.Amount) : 0,
                        JulAmount = list.Where(y => y.Month == 7 && y.Country == country).Count() > 0 ? list.Where(y => y.Month == 7 && y.Country == country).Sum(z => z.Amount) : 0,
                        AugAmount = list.Where(y => y.Month == 8 && y.Country == country).Count() > 0 ? list.Where(y => y.Month == 8 && y.Country == country).Sum(z => z.Amount) : 0,
                        SepAmount = list.Where(y => y.Month == 9 && y.Country == country).Count() > 0 ? list.Where(y => y.Month == 9 && y.Country == country).Sum(z => z.Amount) : 0,
                        OctAmount = list.Where(y => y.Month == 10 && y.Country == country).Count() > 0 ? list.Where(y => y.Month == 10 && y.Country == country).Sum(z => z.Amount) : 0,
                        NovAmount = list.Where(y => y.Month == 11 && y.Country == country).Count() > 0 ? list.Where(y => y.Month == 11 && y.Country == country).Sum(z => z.Amount) : 0,
                        DecAmount = list.Where(y => y.Month == 12 && y.Country == country).Count() > 0 ? list.Where(y => y.Month == 12 && y.Country == country).Sum(z => z.Amount) : 0,
                    }).FirstOrDefault();
                }

                ViewData["CountryData"] = new BranchBO().GetList().Where(x => x.IsActive == true).ToList();
                ViewData["ParticularsData"] = dbContext.Lookups.Where(x => x.LookupCategory == "Particulars").OrderBy(y => y.LookupID).ToList();

                if (reportList.otReportByYear == null)
                    reportList.otReportByYear = new OperationalTransactionReportByYear();
                if (reportList.otReportByMonth == null)
                    reportList.otReportByMonth = new List<OperationalTransactionReportByMonth>();
                return View(reportList);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public ActionResult OperationalExpenses(int year)
        {
            try
            {
                var list = dbContext.usp_OperationalTransactionReport(year).ToList();

                List<OperationalTransactionReportByYear> reportListbyYear = new List<OperationalTransactionReportByYear>();
                var countrylist = new BranchBO().GetList().Where(x => x.IsActive == true).ToList();

                foreach (var item in countrylist)
                {
                    if (list.Where(x => x.Country == item.BranchID).Count() == 0)
                    {
                        reportListbyYear.Add(new OperationalTransactionReportByYear()
                        {
                            Country = item.BranchID,
                            CountryName = item.BranchName,
                            JanAmount = 0,
                            FebAmount = 0,
                            MarAmount = 0,
                            AprAmount = 0,
                            MayAmount = 0,
                            JunAmount = 0,
                            JulAmount = 0,
                            AugAmount = 0,
                            SepAmount = 0,
                            OctAmount = 0,
                            NovAmount = 0,
                            DecAmount = 0
                        });
                    }
                    else
                    {
                        reportListbyYear.Add(new OperationalTransactionReportByYear()
                        {
                            Country = item.BranchID,
                            CountryName = item.BranchName,
                            Year = year,
                            JanAmount = list.Where(y => y.Month == 1 && y.Country == item.BranchID).Count() > 0 ? list.Where(y => y.Month == 1 && y.Country == item.BranchID).Sum(z => z.Amount) : 0,
                            FebAmount = list.Where(y => y.Month == 2 && y.Country == item.BranchID).Count() > 0 ? list.Where(y => y.Month == 2 && y.Country == item.BranchID).Sum(z => z.Amount) : 0,
                            MarAmount = list.Where(y => y.Month == 3 && y.Country == item.BranchID).Count() > 0 ? list.Where(y => y.Month == 3 && y.Country == item.BranchID).Sum(z => z.Amount) : 0,
                            AprAmount = list.Where(y => y.Month == 4 && y.Country == item.BranchID).Count() > 0 ? list.Where(y => y.Month == 4 && y.Country == item.BranchID).Sum(z => z.Amount) : 0,
                            MayAmount = list.Where(y => y.Month == 5 && y.Country == item.BranchID).Count() > 0 ? list.Where(y => y.Month == 5 && y.Country == item.BranchID).Sum(z => z.Amount) : 0,
                            JunAmount = list.Where(y => y.Month == 6 && y.Country == item.BranchID).Count() > 0 ? list.Where(y => y.Month == 6 && y.Country == item.BranchID).Sum(z => z.Amount) : 0,
                            JulAmount = list.Where(y => y.Month == 7 && y.Country == item.BranchID).Count() > 0 ? list.Where(y => y.Month == 7 && y.Country == item.BranchID).Sum(z => z.Amount) : 0,
                            AugAmount = list.Where(y => y.Month == 8 && y.Country == item.BranchID).Count() > 0 ? list.Where(y => y.Month == 8 && y.Country == item.BranchID).Sum(z => z.Amount) : 0,
                            SepAmount = list.Where(y => y.Month == 9 && y.Country == item.BranchID).Count() > 0 ? list.Where(y => y.Month == 9 && y.Country == item.BranchID).Sum(z => z.Amount) : 0,
                            OctAmount = list.Where(y => y.Month == 10 && y.Country == item.BranchID).Count() > 0 ? list.Where(y => y.Month == 10 && y.Country == item.BranchID).Sum(z => z.Amount) : 0,
                            NovAmount = list.Where(y => y.Month == 11 && y.Country == item.BranchID).Count() > 0 ? list.Where(y => y.Month == 11 && y.Country == item.BranchID).Sum(z => z.Amount) : 0,
                            DecAmount = list.Where(y => y.Month == 12 && y.Country == item.BranchID).Count() > 0 ? list.Where(y => y.Month == 12 && y.Country == item.BranchID).Sum(z => z.Amount) : 0,
                        });
                    }
                }

                return View(reportListbyYear.OrderBy(x => x.CountryName));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public ActionResult DashboardOperationaltransaction(Int16 month, int year)
        {
            try
            {
                var list = dbContext.usp_OperationalTransactionReport(year).ToList();

                List<OperationalTransactionReportByMonth> reportListbyMonth = new List<OperationalTransactionReportByMonth>();

                var countrylist = new BranchBO().GetList().Where(x => x.IsActive == true).OrderBy(x => x.BranchName).ToList();

                foreach (var item in countrylist)
                {
                    if (list.Where(x => x.Country == item.BranchID && x.Month == month).Count() == 0)
                    {
                        //reportListbyMonth.Add(new OperationalTransactionReportByMonth()
                        //{
                        //    ParticularName = "",
                        //    Amount = 0,
                        //    Month = month,
                        //    Country = item.BranchID,
                        //    Year = year,

EDU.Web/Views/Dashboard/OperationalExpenses.cshtml
@model IEnumerable<EDU.Web.ViewModels.OperationalTransaction.OperationalTransactionReportByYear>

@{
    ViewBag.Title = "OperationalExpenses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page page-forms-elements">
    <div class="page-wrap">
        <div class="panel panel-default">
            <div class="box" id="grid">
                <div class="box-header">
                    <h4>Operational Expenses - (YTD)</h4>
                    <div class="box-tools">
                        <button type="button" class="btn btn-primary btn-sm waves-effect" data-toggle="modal" onclick="PrintOperationalExpensesList()"><i class="fa fa-print"></i>Print</button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="form-group">
                            <label class="col-md-1 control-label">
                                <span class="pull-right">Year</span>
                            </label>
                            <div class="col-md-2">
                                @Html.DropDownListFor(x => x.FirstOrDefault().Year, Enumerable.Range(2014, 14).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }), new { @class = "form-control input-sm", onchange = "ChangeYear();", @style = "width:60%" })
                            </div>

                        </div>
                        <div class="col-md-12 css10">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-6  css10" id="dvBangladesh">
                                        <div id="jqChart0"></div>
                                    </div>
                                    <div class="col-md-6 css10" id="dvCombodia">
                                        <div id="jqChart1"></div>
                                    </div>
                                    <div class="col-md-6 css10" id="dvMyanmar">
                                        <div id="jqChart4"></div>
                                    </div>
                                    <div class="col-md-6 css10" id="dvSrilanka">
                                        <div id="jqChart8"></div>
                                    </div>

                                    <div class="col-md-6 css10" id="dvPakistan">
                                        <div id="jqChart5"></div>
                                    </div>
                                    <div class="col-md-6 css10" id="dvPhillipines">
                                        <div id="jqChart6"></div>
                                    </div>
                                    <div class="col-md-6 css10" id="dvVietnam">
                                        <div id="jqChart9"></div>
                                    </div>
                                    <div class="col-md-6 css10" id="dvLaos">
                                        <div id="jqChart3"></div>
                                    </div>
                                    <div class="col-md-6 css10" id="dvSingapore">
                                        <div id="jqChart7"></div>
                                    </div>
                                    <div class="col-md-6 css10" id="dvIndia">
                                        <div id="jqChart2"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="myModal" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
</div>

@section SectionScripts{
    
    <script type="text/javascript">
        function ChangeYear() {
            window.location = '@Url.Action("OperationalExpenses", "Dashboard", new { year = ""})' + '?year=' + $('#Year').val();
        };

        function PrintOperationalExpensesList() {
            debugger;
            var country = null;
            @if (Session["AccessRights"].ToString() == "false")
            {
            <text>
                country = @Session["BranchId"].ToString();
            </text>
            }
            var year = $('#Year').val();
            debugger;
            $.ajax({
                url: '@Url.Content("~/Report/OperationalExpensesReport?country=")' + country + '&year=' + year,
                method: 'get',
                contentType: 'text/html',
                success: function (html) {
                    $('#myModal').html(html);
                    $('#myModal').modal('show');
                },
                error: function (err) {
                }
            });
        }

        $(function () {

         @if (Session["UserID"].ToString().ToUpper() == "MGMTSL" || Session["UserID"].ToString().ToUpper() == "ACCSL" || Session["UserID"].ToString().ToUpper() == "CXOSL@EZYINTELLECT.COM")
         {
             <text>
             $('#dvBangladesh').hide();
             $('#dvCombodia').hide();
             $('#dvMyanmar').hide();
             $('#dvPakistan').hide();
             $('#dvPhillipines').hide();
             $('#dvVietnam').hide();
             $('#dvLaos').hide();
             $('#dvSingapore').hide();
             $('#dvIndia').hide();

             </text>
         }
         else if (Session["UserID"].ToString().ToUpper() == "MGMTVN" || Session["UserID"].ToString().ToUpper() == "ACCVN" || Session["UserID"].ToString().ToUpper() == "CXOVN@EZYINTELLECT.COM")
         {
             <text>
             $('#dvBangladesh').hide();
             $('#dvCombodia').hide();
             $('#dvMyanmar').hide();
             $('#dvPakistan').hide();
             $('#dvPhillipines').hide();
             $('#dvSrilanka').hide();
             $('#dvLaos').hide();
             $('#dvSingapore').hide();
             $('#dvIndia').hide();

             </text>
         }
         else if (Session["UserID"].ToString().ToUpper() == "MGMTBD" || Session["UserID"].ToString().ToUpper() == "ACCBD" || Session["UserID"].ToString().ToUpper() == "CXOBD@EZYINTELLECT.COM")
         {
             <text>
             $('#dvSrilanka').hide();
             $('#dvCombodia').hide();
             $('#dvMyanmar').hide();
             $('#dvPakistan').hide();
             $('#dvPhillipines').hide();
             $('#dvVietnam').hide();
             $('#dvLaos').hide();
             $('#dvSingapore').hide();
             $('#dvIndia').hide();

             </text>
         }
         else if (Session["UserID"].ToString().ToUpper() == "MGMTIN" || Session["UserID"].ToString().ToUpper() == "ACCIN" || Session["UserID"].ToString().ToUpper() == "CXOIN@EZYINTELLECT.COM")
         {
             <text>
             $('#dvBangladesh').hide();
             $('#dvCombodia').hide();
             $('#dvMyanmar').hide();
             $('#dvPakistan').hide();
             $('#dvPhillipines').hide();
             $('#dvVietnam').hide();
             $('#dvLaos').hide();
             $('#dvSingapore').hide();
             $('#dvSrilanka').hide();

             </text>
         }
         else if (Session["UserID"].ToString().ToUpper() == "MGMTKH" || Session["UserID"].ToString().ToUpper() == "ACCKH" || Session["UserID"].ToString().ToUpper() == "CXOKH@EZYINTELLECT.COM")
         {
             <text>
             $('#dvBangladesh').hide();
             $('#dvSrilanka').hide();
             $('#dvMyanmar').hide();
             $('#dvPakistan').hide();
             $('#dvPhillipines').hide();
             $('#dvVietnam').hide();
             $('#dvLaos').hide();
             $('#dvSingapore').hide();
             $('#dvIndia').hide();

             </text>
         }
         else if (Session["UserID"].ToString().ToUpper() == "MGMTLA" || Session["UserID"].ToString().ToUpper() == "ACCLA" || Session["UserID"].ToString().ToUpper() == "CXOLA@EZYINTELLECT.COM")
         {
             <text>
             $('#dvBangladesh').hide();
             $('#dvCombodia').hide();
             $('#dvMyanmar').hide();
             $('#dvPakistan').hide();
             $('#dvPhillipines').hide();
             $('#dvVietnam').hide();
             $('#dvSrilanka').hide();
             $('#dvSingapore').hide();
             $('#dvIndia').hide();

             </text>
         }
         else if (Session["UserID"].ToString().ToUpper() == "MGMTMM" || Session["UserID"].ToString().ToUpper() == "ACCMM" || Session["UserID"].ToString().ToUpper() == "CXOMM@EZYINTELLECT.COM")
         {
             <text>
             $('#dvBangladesh').hide();
             $('#dvCombodia').hide();
             $('#dvSrilanka').hide();
             $('#dvPakistan').hide();
             $('#dvPhillipines').hide();
             $('#dvVietnam').hide();
             $('#dvLaos').hide();
             $('#dvSingapore').hide();
             $('#dvIndia').hide();

             </text>
         }
         else if (Session["UserID"].ToString().ToUpper() == "MGMTPH" || Session["UserID"].ToString().ToUpper() == "ACCPH" || Session["UserID"].ToString().ToUpper() == "CXOPH@EZYINTELLECT.COM")
         {
             <text>
             $('#dvBangladesh').hide();
             $('#dvCombodia').hide();
             $('#dvMyanmar').hide();
             $('#dvPakistan').hide();
             $('#dvSrilanka').hide();
             $('#dvVietnam').hide();
             $('#dvLaos').hide();
             $('#dvSingapore').hide();
             $('#dvIndia').hide();

             </text>
         }
         else if (Session["UserID"].ToString().ToUpper() == "MGMTPK" || Session["UserID"].ToString().ToUpper() == "ACCPA" || Session["UserID"].ToString().ToUpper() == "CXOPK@EZYINTELLECT.COM")
         {
             <text>
             $('#dvBangladesh').hide();
             $('#dvCombodia').hide();
             $('#dvMyanmar').hide();
             $('#dvSrilanka').hide();
             $('#dvPhillipines').hide();
             $('#dvVietnam').hide();
             $('#dvLaos').hide();
             $('#dvSingapore').hide();
             $('#dvIndia').hide();

             </text>
         }

            $('#liDashboardOperationalExpenses').addClass('active');
            var count = 0;
            @foreach (var item in Model)
            {
                <text>
            $('#jqChart' + count).jqChart({
                title: {
                    text: '@item.CountryName',
                    font: '14px sans-serif'
                },
                animation: { duration: 1 },
                border: { visible: false },
                shadows: {
                    enabled: true
                },
                legend: {
                    visible: false
                },
                series: [
                    {
                        type: 'column',
                        fillStyles: ['#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970'],
                        data: [
                            ['JAN', @item.JanAmount], ['FEB', @item.FebAmount], ['MAR', @item.MarAmount],
                        ['APR', @item.AprAmount], ['MAY', @item.MayAmount], ['JUN', @item.JunAmount], ['JUL', @item.JulAmount],
                        ['AUG', @item.AugAmount], ['SEP', @item.SepAmount], ['OCT', @item.OctAmount], ['NOV', @item.NovAmount], ['DEC', @item.DecAmount]
                        ]
                    }
                ]
            });
            $('#jqChart' + count).bind('tooltipFormat', function (e, data) {
                return "<b>" + data.x + "</b><br />" +
                       "$ " + data.y + "<br />";
            });
            count++;
            </text>
                }
        });
    </script>
}