EDU.Web/Models/OperationalTransaction.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationalTransaction
    {
        public int OperationalTransactionId { get; set; }
        public int CategoryId { get; set; }
        public int ParticularsId { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<short> Month { get; set; }
        public decimal Amount { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public short Country { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> OperationId { get; set; }
    }
}

EDU.Web/ViewModels/OperationalTransaction/OperationalTransactionReportVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EDU.Web.ViewModels.OperationalTransaction
{
    public class OperationalTransactionReportVM
    {
        public List<OperationalTransactionReportByMonth> otReportByMonth { get; set; }
        public OperationalTransactionReportByYear otReportByYear { get; set; }
    }

    public class OperationalTransactionReportByMonth
    {
        public int ParticularId { get; set; }
        public string ParticularName { get; set; }
        public decimal Amount { get; set; }
        public Nullable<short> Month { get; set; }
        public short Country { get; set; }
        public string CountryName { get; set; }
        public int Year { get; set; }
    }

    public class OperationalTransactionReportByYear
    {
        public short Country { get; set; }
        public string CountryName { get; set; }
        public int Year { get; set; }
        public decimal JanAmount { get; set; }
        public decimal FebAmount { get; set; }
        public decimal MarAmount { get; set; }
        public decimal AprAmount { get; set; }
        public decimal MayAmount { get; set; }
        public decimal JunAmount { get; set; }
        public decimal JulAmount { get; set; }
        public decimal AugAmount { get; set; }
        public decimal SepAmount { get; set; }
        public decimal OctAmount { get; set; }
        public decimal NovAmount { get; set; }
        public decimal DecAmount { get; set; }
    }
}

EDU.Web/ViewModels/OperationalTransaction/OperationalTransactionVM.cs
using EDU.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EDU.Web.ViewModels.OperationalTransactionModel
{
    public class OperationalTransactionVM
    {
        public int OperationalTransactionId { get; set; }
        public int CategoryId { get; set; }
        public int ParticularsId { get; set; }
        public int? Year { get; set; }
        public Nullable<short> Month { get; set; }
        public decimal Amount { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CategoryIdDesc { get; set; }
        public string ParticularsIdDesc { get; set; }
        public string MonthDesc { get; set; }
        public short Country { get; set; }
        public string CountryName { get; set; }
        public int? OperationId { get; set; }
    }

    public class OperationalTransactionReportVM
    {
        public int CategoryId { get; set; }
        public int ParticularsId { get; set; }
        public int? Year { get; set; }
        public string CategoryIdDesc { get; set; }
        public string ParticularsIdDesc { get; set; }
        public decimal? AprAmount { get; set; }
        public decimal? MayAmount { get; set; }
        public decimal? JuneAmount { get; set; }
        public decimal? JulyAmount { get; set; }
        public decimal? AugAmount { get; set; }
        public decimal? SepAmount { get; set; }
        public decimal? OctAmount { get; set; }
        public decimal? NovAmount { get; set; }
        public decimal? DecAmount { get; set; }
        public decimal? JanAmount { get; set; }
        public decimal? FebAmount { get; set; }
        public decimal? MarAmount { get; set; }
        public decimal? YTD { get; set; }
        public short Country { get; set; }
        public string CountryName { get; set; }
        public int? OperationId { get; set; }
    }


    public class OTVM
    {
        public int OperationalTransactionId { get; set; }
        public int OperationalExpId { get; set; }
        public int OtherExpId { get; set; }
        public int? Year { get; set; }
        public Nullable<short> Month { get; set; }

        public int SalariesId { get; set; }
        public int TravellingexpId { get; set; }
        public int RentalId { get; set; }
        public int TelephoneexpId { get; set; }
        public int CourierchargesId { get; set; }
        public int InsuranceId { get; set; }
        public int UtilityId { get; set; }
        public int MarketingexpId { get; set; }
        public int DepreciationId { get; set; }
        public int LegalexpId { get; set; }
        public int RepairmaintenanceId { get; set; }
        public int BankchargesId { get; set; }
        public int PrintingstationeryId { get; set; }
        public int StaffwelfareId { get; set; }
        public int OtherexpensesincomeId { get; set; }

        public decimal SalariesAmount { get; set; }
        public decimal TravellingexpAmount { get; set; }
        public decimal RentalAmount { get; set; }
        public decimal TelephoneexpAmount { get; set; }
        public decimal CourierchargesAmount { get; set; }
        public decimal InsuranceAmount { get; set; }
        public decimal UtilityAmount { get; set; }
        public decimal MarketingexpAmount { get; set; }
        public decimal DepreciationAmount { get; set; }
        public decimal LegalexpAmount { get; set; }
        public decimal RepairmaintenanceAmount { get; set; }
        public decimal BankchargesAmount { get; set; }
        public decimal PrintingstationeryAmount { get; set; }
        public decimal StaffwelfareAmount { get; set; }
        public decimal OtherexpensesincomeAmount { get; set; }
        public bool IsActive { get; set; }
        public short Country { get; set; }
        public string CountryName { get; set; }
        public int? OperationId { get; set; }
    }
}

EDU.Web/Controllers/OperationalTransactionController.cs
using EDU.Web.Models;
using EDU.Web.ViewModels.OperationalTransactionModel;
using EZY.EDU.BusinessFactory;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EDU.Web.Controllers
{
    [SessionFilter]
    public class OperationalTransactionController : BaseController
    {
        EducationEntities dbContext = new EducationEntities();

        // GET: OperationalTransaction
        public ActionResult OperationalTransactionList(short? month, int year, int country)
        {
            List<OperationalTransactionVM> list = dbContext.OperationalTransactions
                .Where(x => x.IsActive == true && x.Month == month && x.Year == year && x.Country == country)
                .Select(y => new OperationalTransactionVM
                {
                    OperationId = y.OperationId,
                    OperationalTransactionId = y.OperationalTransactionId,
                    CategoryId = y.CategoryId,
                    ParticularsId = y.ParticularsId,
                    Country = y.Country,
                    CountryName = y.CountryName,
                    Month = y.Month,
                    Year = y.Year,
                    Amount = y.Amount,
                    IsActive = y.IsActive,
                    CreatedBy = y.CreatedBy,
                    CreatedOn = y.CreatedOn,
                    ModifiedBy = y.ModifiedBy,
                    ModifiedOn = y.ModifiedOn,
                    CategoryIdDesc = dbContext.Lookups.Where(c => c.LookupID == y.CategoryId).FirstOrDefault().LookupDescription,
                    ParticularsIdDesc = dbContext.Lookups.Where(c => c.LookupID == y.ParticularsId).FirstOrDefault().LookupDescription
                })
                .ToList();

            decimal? totalAmount = list.Sum(x => x.Amount);


            ViewData["totalAmount"] = totalAmount;

            ViewData["CountryData"] = new BranchBO().GetList();
            return View(list);
        }

        [HttpGet]
        public ActionResult OperationalTransaction(int? operationId, short? month, int? year, short country)
        {
            OTVM operationalTransactionvm = new OTVM();
            if (operationId == -1)
            {
                ViewBag.Title = "New Operational Transaction";
                operationalTransactionvm.OperationalTransactionId = -1;
                operationalTransactionvm.OperationId = -1;

                operationalTransactionvm.OperationalExpId = 1100;
                operationalTransactionvm.OtherExpId = 1101;
                operationalTransactionvm.Year = year;
                operationalTransactionvm.Month = month;

                operationalTransactionvm.SalariesId = 1200;
                operationalTransactionvm.SalariesAmount = 0;

                operationalTransactionvm.TravellingexpId = 1201;
                operationalTransactionvm.TravellingexpAmount = 0;

                operationalTransactionvm.RentalId = 1202;
                operationalTransactionvm.RentalAmount = 0;

                operationalTransactionvm.TelephoneexpId = 1203;
                operationalTransactionvm.TelephoneexpAmount = 0;

                operationalTransactionvm.CourierchargesId = 1204;
                operationalTransactionvm.CourierchargesAmount = 0;

                operationalTransactionvm.InsuranceId = 1205;
                operationalTransactionvm.InsuranceAmount = 0;

                operationalTransactionvm.UtilityId = 1206;
                operationalTransactionvm.UtilityAmount = 0;

                operationalTransactionvm.MarketingexpId = 1207;
                operationalTransactionvm.MarketingexpAmount = 0;

                operationalTransactionvm.DepreciationId = 1208;
                operationalTransactionvm.DepreciationAmount = 0;

                operationalTransactionvm.LegalexpId = 1300;
                operationalTransactionvm.LegalexpAmount = 0;

                operationalTransactionvm.RepairmaintenanceId = 1301;
                operationalTransactionvm.RepairmaintenanceAmount = 0;

                operationalTransactionvm.BankchargesId = 1302;
                operationalTransactionvm.BankchargesAmount = 0;

                operationalTransactionvm.PrintingstationeryId = 1303;
                operationalTransactionvm.PrintingstationeryAmount = 0;

                operationalTransactionvm.StaffwelfareId = 1304;
                operationalTransactionvm.StaffwelfareAmount = 0;

                operationalTransactionvm.OtherexpensesincomeId = 1305;
                operationalTransactionvm.OtherexpensesincomeAmount = 0;

                operationalTransactionvm.Country = country;
            }
            else
            {
                ViewBag.Title = "Update Operational Transaction";
                //operationalTransactionvm.OperationalTransactionId = -1;
                List<OperationalTransaction> otList = dbContext.OperationalTransactions.Where(x => x.OperationId == operationId && x.Country == country && x.IsActive == true).ToList();

                operationalTransactionvm.OperationId = operationId;

                operationalTransactionvm.OperationalExpId = 1100;
                operationalTransactionvm.OtherExpId = 1101;
                operationalTransactionvm.Year = year;
                operationalTransactionvm.Month = month;

                operationalTransactionvm.SalariesId = 1200;
                operationalTransactionvm.SalariesAmount = otList.Where(x => x.ParticularsId == 1200).FirstOrDefault().Amount;

                operationalTransactionvm.TravellingexpId = 1201;
                operationalTransactionvm.TravellingexpAmount = otList.Where(x => x.ParticularsId == 1201).FirstOrDefault().Amount;

                operationalTransactionvm.RentalId = 1202;
                operationalTransactionvm.RentalAmount = otList.Where(x => x.ParticularsId == 1202).FirstOrDefault().Amount;

                operationalTransactionvm.TelephoneexpId = 1203;
                operationalTransactionvm.TelephoneexpAmount = otList.Where(x => x.ParticularsId == 1203).FirstOrDefault().Amount;

                operationalTransactionvm.CourierchargesId = 1204;
                operationalTransactionvm.CourierchargesAmount = otList.Where(x => x.ParticularsId == 1204).FirstOrDefault().Amount;

                operationalTransactionvm.InsuranceId = 1205;
                operationalTransactionvm.InsuranceAmount = otList.Where(x => x.ParticularsId == 1205).FirstOrDefault().Amount;

                operationalTransactionvm.UtilityId = 1206;
                operationalTransactionvm.UtilityAmount = otList.Where(x => x.ParticularsId == 1206).FirstOrDefault().Amount;

                operationalTransactionvm.MarketingexpId = 1207;
                operationalTransactionvm.MarketingexpAmount = otList.Where(x => x.ParticularsId == 1207).FirstOrDefault().Amount;

                operationalTransactionvm.DepreciationId = 1208;
                operationalTransactionvm.DepreciationAmount = otList.Where(x => x.ParticularsId == 1208).FirstOrDefault().Amount;

                operationalTransactionvm.LegalexpId = 1300;
                operationalTransactionvm.LegalexpAmount = otList.Where(x => x.ParticularsId == 1300).FirstOrDefault().Amount;

                operationalTransactionvm.RepairmaintenanceId = 1301;
                operationalTransactionvm.RepairmaintenanceAmount = otList.Where(x => x.ParticularsId == 1301).FirstOrDefault().Amount;

                operationalTransactionvm.BankchargesId = 1302;
                operationalTransactionvm.BankchargesAmount = otList.Where(x => x.ParticularsId == 1302).FirstOrDefault().Amount;

                operationalTransactionvm.PrintingstationeryId = 1303;
                operationalTransactionvm.PrintingstationeryAmount = otList.Where(x => x.ParticularsId == 1303).FirstOrDefault().Amount;

                operationalTransactionvm.StaffwelfareId = 1304;
                operationalTransactionvm.StaffwelfareAmount = otList.Where(x => x.ParticularsId == 1304).FirstOrDefault().Amount;

                operationalTransactionvm.OtherexpensesincomeId = 1305;
                operationalTransactionvm.OtherexpensesincomeAmount = otList.Where(x => x.ParticularsId == 1305).FirstOrDefault().Amount;

                operationalTransactionvm.Country = country;
            }

            ViewData["CountryData"] = new BranchBO().GetList();
            return View(operationalTransactionvm);
        }

        [HttpPost]
        public ActionResult SaveOperationalTransaction(OTVM otvm)
        {
            try
            {
                string countryname = otvm.Country > 0 ? new BranchBO().GetList().Where(x => x.BranchID == otvm.Country).FirstOrDefault().BranchName : "";
                OperationalTransaction operationalTransactionInfo = new OperationalTransaction();
                List<OperationalTransaction> otList = new List<OperationalTransaction>();

                if (otvm.OperationId == -1)
                {
                    operationalTransactionInfo.OperationId = Convert.ToInt32(otvm.Year.ToString() + otvm.Month.ToString());
                    operationalTransactionInfo.Country = otvm.Country;
                    operationalTransactionInfo.CountryName = countryname;
                    operationalTransactionInfo.Year = otvm.Year;
                    operationalTransactionInfo.Month = otvm.Month;

                    operationalTransactionInfo.CreatedBy = USER_ID;
                    operationalTransactionInfo.CreatedOn = UTILITY.SINGAPORETIME;
                    operationalTransactionInfo.IsActive = true;

                    Dictionary<int, decimal?> PerticularsList = new Dictionary<int, decimal?>();
                    PerticularsList.Add(otvm.SalariesId, otvm.SalariesAmount);
                    PerticularsList.Add(otvm.TravellingexpId, otvm.TravellingexpAmount);
                    PerticularsList.Add(otvm.RentalId, otvm.RentalAmount);

EDU.Web/Views/OperationalTransaction/OperationalTransactionList.cshtml
@using System.Globalization;
@model IEnumerable<EDU.Web.ViewModels.OperationalTransactionModel.OperationalTransactionVM>
@{
    ViewBag.Title = "OperationalTransactionList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    var grid = new WebGrid(Model, rowsPerPage: 50);
    grid.Pager(WebGridPagerModes.All);

    var count = Model.Count();
}
@functions {

    public string ConvertToInt64dollar(decimal? data)
    {
        if (data != null && data > 0)
            return new HtmlString("$ " + Convert.ToInt64(data.Value)).ToString();
        else
            return null;
    }
}
@{

    var listMonths = new List<SelectListItem>()
                          {

                           new SelectListItem {Text = "January",   Value = "1"},
                           new SelectListItem {Text = "February", Value = "2"},
                           new SelectListItem {Text = "March", Value = "3"},
                           new SelectListItem {Text = "April",   Value = "4"},
                           new SelectListItem {Text = "May", Value = "5"},
                           new SelectListItem {Text = "June", Value = "6"},
                           new SelectListItem {Text = "July",   Value = "7"},
                           new SelectListItem {Text = "August", Value = "8"},
                           new SelectListItem {Text = "September", Value = "9"},
                           new SelectListItem {Text = "October",   Value = "10"},
                           new SelectListItem {Text = "November", Value = "11"},
                           new SelectListItem {Text = "December", Value = "12"}
                       };


}
<style>
    .bordertop {
        border-top: 2px solid gray !important;
        border-bottom: 2px solid gray !important;
        color: #D73925;
        /*font-family: 'Bebas Neue'*/
    }

    .center {
        text-align: center !important;
    }
</style>
<div class="page page-forms-elements">
    <div class="page-wrap">
        <div class="panel panel-default">
            <div class="box" id="grid">
                <div class="box-header">
                    <h4>Operational Transaction List</h4>
                    <div class="box-tools" style="right:180px">
                        <button type="button" class="btn btn-primary btn-sm waves-effect" data-toggle="modal" onclick="PrintDashboardOperationaltransactionList()"><i class="fa fa-print"></i>Print</button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="form-group">
                            <label class="col-md-1 col-md-offset-1 control-label">
                                <span class="pull-right">Country</span>
                            </label>
                            <div class="col-md-2">
                                @Html.HiddenFor(x => x.FirstOrDefault().CountryName)
                                @Html.HiddenFor(x => x.FirstOrDefault().OperationId)
                                @Html.DropDownListFor(x => x.FirstOrDefault().Country,
new SelectList((List<EZY.EDU.Contract.Branch>)ViewData["CountryData"], "BranchId", "BranchName"), new { @class = "form-control input-sm", onchange = "ChangeMonth();" })
                            </div>
                            <div class="col-md-2">
                                <div style="width:30%;float:left">
                                    <label class="control-label">
                                        <span class="pull-left">Year</span>
                                    </label>
                                </div>
                                <div style="width:70%; float:left">
                                    @Html.DropDownListFor(x => x.FirstOrDefault().Year, Enumerable.Range(2014, 14).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }), new { @class = "form-control input-sm", onchange = "ChangeMonth();", @style = "width:100%" })
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div style="width:30%;float:left">
                                    <label class="control-label">
                                        <span class="pull-left">Month</span>
                                    </label>
                                </div>
                                <div style="width:70%; float:left">
                                    @Html.DropDownListFor(x => x.FirstOrDefault().Month, listMonths, new { @class = "form-control input-sm pull-right", onchange = "ChangeMonth();", @style = "width:100%" })
                                </div>
                            </div>
                            <div class="col-md-1">
                                @if (Session["RoleCode"].ToString() == "ADMIN" || Session["RoleCode"].ToString() == "FINANCE")
                                {
                                    if (Model.FirstOrDefault() == null)
                                    {
                                        <button type="button" id="btnAdd" class="btn btn-info btn-sm waves-effect" onclick="AddOperationalTransaction()"><i class="fa fa-plus"></i>Add Operational Transactions</button>
                                    }
                                    else
                                    {
                                        <button type="button" id="btnAdd" class="btn btn-info btn-sm waves-effect" onclick="AddOperationalTransaction()"><i class="fa fa-pencil"></i>Update Operational Transactions</button>
                                    }
                                }
                            </div>
                        </div>
                    </div>
                    <hr />
                    <div class="row css25">
                        <div class="col-md-8 col-md-offset-2 ">
                            <div id="gridContent">
                                @grid.GetHtml(
                                          columns: grid.Columns(
                                          grid.Column("CategoryIdDesc", "Category", canSort: true),
                                          grid.Column("ParticularsIdDesc", "Particulars", canSort: true),
                                          grid.Column("Amount", "Amount", canSort: true,
                                               format:
                                            @<text>
                                                <div style='width:100%;'>
                                                    <span class="center">
                                                        @ConvertToInt64dollar(item.Amount)
                                                    </span>
                                                </div>
                                            </text>, style: "center")),
  tableStyle: "table table-striped table-bordered")
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="myModal" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
</div>

@section SectionScripts
    {
    <script type="text/javascript">

        $(function () {

            @if (Model.Count() > 0 && Model.FirstOrDefault().OperationId == -1)
            {
                if (Session["AccessRights"].ToString() == "false")
                {
                <text>
                    $("#Country").select2().select2("val", @Session["BranchId"].ToString());
                    $('#Country').attr('disabled', 'disabled');
                </text>
                }
            }
            else
            {
                if (Session["AccessRights"].ToString() == "false")
                {
                <text>
                    $('#Country').attr('disabled', 'disabled');
                </text>
                }
            }

            $('#liOperationalTransactionList').addClass('active');
            var totalAmount = "$ " + @ViewData["totalAmount"].ToString();
            @if (count > 0)
        {
            <text>
            $('#gridContent tbody').append('<tr class="bordertop"><td>Total Opex</td><td></td><td class="center">' + totalAmount + '</td><tr>');
             </text>
             }
        });

        function PrintDashboardOperationaltransactionList() {
            debugger;
            var country = null;
            @if (Session["AccessRights"].ToString() == "false")
            {<text>
            country = @Session["BranchId"].ToString();
            </text>
            }
            var year = $('#Year').val();
            var month = $('#Month').val();
            debugger;
            $.ajax({
                url: '@Url.Content("~/Report/DashboardOperationalTransactionReport?country=")' + country + '&year=' + year + '&month=' + month,
                method: 'get',
                contentType: 'text/html',
                success: function (html) {
                    $('#myModal').html(html);
                    $('#myModal').modal('show');
                },
                error: function (err) {
                }
            });
        }

        function ChangeMonth() {
            debugger;
            window.location = '@Url.Action("OperationalTransactionList", "OperationalTransaction", new { month = "", year = "" })' + '?month=' + $('#Month').val() + "&year=" + $('#Year').val() + "&country=" + $('#Country').val();
        };

        function AddOperationalTransaction() {
            var operationId = $('#OperationId').val() == '' ? -1 : $('#OperationId').val();
            debugger;
            location.href = '@Url.Content("~/OperationalTransaction/OperationalTransaction?operationId=")' + operationId+"&month=" + $('#Month').val() + "&year=" + $('#Year').val() + "&country=" + $('#Country').val();

            @*if ($('#frmOperationalTransaction').valid()) {
                location.href = '@Url.Content("~/OperationalTransaction/OperationalTransaction?operationId=")' + "-1&month=" + $('#Month').val() + "&year=" + $('#Year').val() + "&country=" + $('#Country').val();
            }*@
        }



        //$('#frmOperationalTransaction').validate({
        //    rules: {
        //        Country: {
        //            required: true
        //        },
        //        CategoryId: {
        //            required: true
        //        },
        //        ParticularsId: {
        //            required: true
        //        },
        //        Amount: {
        //            required: true
        //        },

        //    }
        //});


    </script>
}